
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOC PA PF STRING SUBTIT TIT\nDocumento : PA DOC Lista PF\nLista : Elem Lista\n        | Elem\nElem : PA TIT STRING PF\n        | PA SUBTIT STRING PF\n        | STRING\n'
    
_lr_action_items = {'PA':([0,3,6,7,14,15,],[2,4,4,-6,-4,-5,]),'$end':([1,10,],[0,-1,]),'DOC':([2,],[3,]),'STRING':([3,6,7,8,9,14,15,],[7,7,-6,12,13,-4,-5,]),'TIT':([4,],[8,]),'SUBTIT':([4,],[9,]),'PF':([5,6,7,11,12,13,14,15,],[10,-3,-6,-2,14,15,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Documento':([0,],[1,]),'Lista':([3,6,],[5,11,]),'Elem':([3,6,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Documento","S'",1,None,None,None),
  ('Documento -> PA DOC Lista PF','Documento',4,'p_gramatical','lmd_sin.py',6),
  ('Lista -> Elem Lista','Lista',2,'p_gramatical','lmd_sin.py',7),
  ('Lista -> Elem','Lista',1,'p_gramatical','lmd_sin.py',8),
  ('Elem -> PA TIT STRING PF','Elem',4,'p_gramatical','lmd_sin.py',9),
  ('Elem -> PA SUBTIT STRING PF','Elem',4,'p_gramatical','lmd_sin.py',10),
  ('Elem -> STRING','Elem',1,'p_gramatical','lmd_sin.py',11),
]
