
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CAST GENRES TITTLE YEAR num stringCinema : '[' Lista ']'Lista : Lista ',' FilmeLista : FilmeFilme : '{' Titulo ',' Ano ',' Elenco ',' Generos '}'Titulo : TITTLE stringAno : YEAR numElenco : CAST '[' ListaAtor ']'ListaAtor : ListaAtor ',' stringListaAtor : stringGeneros : GENRES '[' ListaGeneros ']'ListaGeneros : ListaGeneros ',' stringListaGeneros : string"
    
_lr_action_items = {'[':([0,18,22,],[2,20,26,]),'$end':([1,6,],[0,-1,]),'{':([2,7,],[5,5,]),']':([3,4,10,23,24,25,29,30,31,34,],[6,-3,-2,27,-9,-4,32,-12,-8,-11,]),',':([3,4,8,10,12,13,16,17,23,24,25,27,29,30,31,34,],[7,-3,11,-2,-5,15,-6,19,28,-9,-4,-7,33,-12,-8,-11,]),'TITTLE':([5,],[9,]),'string':([9,20,26,28,33,],[12,24,30,31,34,]),'YEAR':([11,],[14,]),'num':([14,],[16,]),'CAST':([15,],[18,]),'GENRES':([19,],[22,]),'}':([21,32,],[25,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Cinema':([0,],[1,]),'Lista':([2,],[3,]),'Filme':([2,7,],[4,10,]),'Titulo':([5,],[8,]),'Ano':([11,],[13,]),'Elenco':([15,],[17,]),'Generos':([19,],[21,]),'ListaAtor':([20,],[23,]),'ListaGeneros':([26,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Cinema","S'",1,None,None,None),
  ('Cinema -> [ Lista ]','Cinema',3,'p_Cinema','parser.py',6),
  ('Lista -> Lista , Filme','Lista',3,'p_Lista_lista','parser.py',9),
  ('Lista -> Filme','Lista',1,'p_Lista_elem','parser.py',12),
  ('Filme -> { Titulo , Ano , Elenco , Generos }','Filme',9,'p_Filme','parser.py',15),
  ('Titulo -> TITTLE string','Titulo',2,'p_Titulo','parser.py',18),
  ('Ano -> YEAR num','Ano',2,'p_Ano','parser.py',21),
  ('Elenco -> CAST [ ListaAtor ]','Elenco',4,'p_Elenco','parser.py',24),
  ('ListaAtor -> ListaAtor , string','ListaAtor',3,'p_ListaAtor_lista','parser.py',27),
  ('ListaAtor -> string','ListaAtor',1,'p_ListaAtor_elem','parser.py',30),
  ('Generos -> GENRES [ ListaGeneros ]','Generos',4,'p_Generos','parser.py',33),
  ('ListaGeneros -> ListaGeneros , string','ListaGeneros',3,'p_ListaGeneros_lista','parser.py',36),
  ('ListaGeneros -> string','ListaGeneros',1,'p_ListaGeneros_elem','parser.py',39),
]
